spring:
  profiles: dev
  application:
    name: user-provider # 多个服务提供者共用一个应用名

server:
  port: 8001

eureka:
  instance:
    instance-id: springcloud-provider-8001
    prefer-ip-address: true # 访问路径显示ip地址
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ # Eureka Server服务器地址
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream # 开启hystrix监控，否则访问 http://localhost:8001/actuator/hystrix.stream 会报404
